// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc5CwQlCqZc3djgC7UT-sCVbT97X3PWpI',
    appId: '1:456558025436:web:81ee3cb1075d4c93a73219',
    messagingSenderId: '456558025436',
    projectId: 'flutter-59efb',
    authDomain: 'flutter-59efb.firebaseapp.com',
    storageBucket: 'flutter-59efb.firebasestorage.app',
    measurementId: 'G-6G1G1KFKR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7WGH52pzrDYYAcfhI_JEVZUZoN7Kxrs',
    appId: '1:456558025436:android:ffb54baa3699a5b1a73219',
    messagingSenderId: '456558025436',
    projectId: 'flutter-59efb',
    storageBucket: 'flutter-59efb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlrjESDnwBkxY4PxolBV05oqsaLLRlXAY',
    appId: '1:456558025436:ios:66f8d0e62dab3779a73219',
    messagingSenderId: '456558025436',
    projectId: 'flutter-59efb',
    storageBucket: 'flutter-59efb.firebasestorage.app',
    iosBundleId: 'com.example.commandAppFt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlrjESDnwBkxY4PxolBV05oqsaLLRlXAY',
    appId: '1:456558025436:ios:66f8d0e62dab3779a73219',
    messagingSenderId: '456558025436',
    projectId: 'flutter-59efb',
    storageBucket: 'flutter-59efb.firebasestorage.app',
    iosBundleId: 'com.example.commandAppFt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc5CwQlCqZc3djgC7UT-sCVbT97X3PWpI',
    appId: '1:456558025436:web:9a118383d8ce1e00a73219',
    messagingSenderId: '456558025436',
    projectId: 'flutter-59efb',
    authDomain: 'flutter-59efb.firebaseapp.com',
    storageBucket: 'flutter-59efb.firebasestorage.app',
    measurementId: 'G-5Y0J7JV37H',
  );

}